# Regression tests
# To include the pages in /_tests in the local build, run jekyll with the option
# --config _config.yml,_config_dev.yml,_tests.yml

# Define Jekyll collections
collections:
  tests:
    permalink: "/:collection/:path:output_ext"
    output: true
  components_header:
    permalink: "/:collection/:path:output_ext"
    output: true
  components_layout:
    permalink: "/:collection/:path:output_ext"
    output: true
  components_main:
    permalink: "/:collection/:path:output_ext"
    output: true
  components_smarty:
    permalink: "/:collection/:path:output_ext"
    output: true
  components_smarty:
    permalink: "/:collection/:path:output_ext"
    output: true

just_the_docs:
  collections:
    tests:
      name: Components
      nav_exclude: false
      nav_fold: true
      search_exclude: true
    components_header:
      name: Header
      nav_exclude: false
      nav_fold: true
      search_exclude: true
    components_layout:
      name: Layout
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    components_main:
      name: Main
      nav_exclude: false
      nav_fold: false
      search_exclude: true
    components_smarty:
      name: Smarty
      nav_exclude: true
      search_exclude: false
    components_templates:
      name: Templates
      nav_exclude: true
      search_exclude: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "tests"
    values:
      layout: "default"

# callouts_opacity: 0.15
# callouts_level: loud

callouts:
  admonition:
    # title:
    color: grey-lt
  attention:
    title: Attention
    color: purple
  caution:
    title: Caution
    color: yellow
  custom:
    title: Custom
    color: pink
    opacity: 0.3
  danger:
    title: Danger
    color: red
  error:
    title: Error
    color: red
  highlight:
    color: yellow
    opacity: 0.5
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: green
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: grey-dk
  warning:
    title: Warning
    color: red
